# 01 — Entendimiento de los datos ENSO

## Objetivo

Explorar y comprender las series climáticas obtenidas de NOAA Physical
Sciences Laboratory antes de realizar cualquier transformación.

Variables disponibles:

- Niño 1+2
- Niño 3
- Niño 3.4
- Niño 4
- Southern Oscillation Index (SOI)
- Trans-Niño Index (TNI)
- Multivariate ENSO Index v2 (MEI.v2)
- Oceanic Niño Index (ONI)

En esta etapa se analizarán:

1. Formato y estructura de los archivos.
2. Período temporal disponible.
3. Variables y tipos de datos.
4. Valores faltantes.
5. Diferencias entre las fuentes.

In [2]:
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# rutas de los datos
PROJECT_ROOT = Path.cwd().parent
DATA_RAW = PROJECT_ROOT / "data" / "raw"

DATA_RAW

PosixPath('/home/gustavo-paredes/Documents/Developer/Yachay/enso-ml/data/raw')

In [4]:
# primer vistazo de los datos
for file in sorted(DATA_RAW.iterdir()):
    print(file.name)

meiv2.data
nino12.long.anom.csv
nino3.long.anom.csv
nino34.long.anom.csv
nino4.long.anom.csv
oni.txt
soi.long.csv
tni.long.csv

Revisar los datos que contiene cada archivo

empezamos con nino34

In [5]:
nino34 = pd.read_csv(DATA_RAW / "nino34.long.anom.csv")
nino34.head()

,Date,NINA34 missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0,1870-01-01,-1.00
1,1870-02-01,-1.20
2,1870-03-01,-0.83
3,1870-04-01,-0.81
4,1870-05-01,-1.27

In [6]:
nino34.shape

(1884, 2)

In [7]:
nino34.columns

Index(['Date', '   NINA34  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/'], dtype='str')

In [8]:
nino34.dtypes

Date                                                                               str
   NINA34  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/    float64
dtype: object

In [9]:
nino34.tail()

,Date,NINA34 missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
1879,2026-08-01,-9999.0
1880,2026-09-01,-9999.0
1881,2026-10-01,-9999.0
1882,2026-11-01,-9999.0
1883,2026-12-01,-9999.0

inspeccion de los 4 indices nino en conjunto

In [10]:
nino12 = pd.read_csv(DATA_RAW / "nino12.long.anom.csv")
nino3 = pd.read_csv(DATA_RAW / "nino3.long.anom.csv")
nino34 = pd.read_csv(DATA_RAW / "nino34.long.anom.csv")
nino4 = pd.read_csv(DATA_RAW / "nino4.long.anom.csv")

Descripcion de los datos

In [11]:
datasets_nino = {
    "Niño 1+2": nino12,
    "Niño 3": nino3,
    "Niño 3.4": nino34,
    "Niño 4": nino4,
}

for name, df in datasets_nino.items():
    print(f"\n{name}")
    print(f"Shape: {df.shape}")
    print(f"Columnas: {df.columns.tolist()}")

Niño 1+2
Shape: (1884, 2)
Columnas: ['Date', '   NINA12  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']

Niño 3
Shape: (1884, 2)
Columnas: ['Date', '   NINA3  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']

Niño 3.4
Shape: (1884, 2)
Columnas: ['Date', '   NINA34  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']

Niño 4
Shape: (1884, 2)
Columnas: ['Date', '   NINA4  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']

Exploracion inicial de SOI y TNI

In [12]:
soi = pd.read_csv(DATA_RAW / "soi.long.csv")
tni = pd.read_csv(DATA_RAW / "tni.long.csv")

In [13]:
soi.head()

,Date,SOI from CRU missing value 0.47 https://psl.noaa.gov/data/timeseries/month/
0,1866-01-01,-0.62
1,1866-02-01,-0.12
2,1866-03-01,-0.62
3,1866-04-01,-0.65
4,1866-05-01,0.04

In [14]:
tni.head()

,Date,TNI missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0,1870-01-01,-9999.000
1,1870-02-01,-9999.000
2,1870-03-01,0.834
3,1870-04-01,1.127
4,1870-05-01,0.863

In [15]:
print("SOI:", soi.shape)
print("TNI:", tni.shape)

SOI: (1920, 2)
TNI: (1884, 2)

Valores raros o sospechosos

In [16]:
for name, df in {
    **datasets_nino,
    "SOI": soi,
    "TNI": tni,
}.items():
    print(f"\n{name}")
    print(df.describe())

Niño 1+2
       NINA12  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
count                                        1884.000000
mean                                          -31.953923
std                                           563.521056
min                                         -9999.000000
25%                                            -0.740000
50%                                            -0.250000
75%                                             0.330000
max                                             4.560000

Niño 3
       NINA3  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
count                                        1884.000000
mean                                          -31.977240
std                                           563.519573
min                                         -9999.000000
25%                                            -0.700000
50%                                            -0.230000
75%                                             0.280000
max                                             3.240000

Niño 3.4
       NINA34  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
count                                        1884.000000
mean                                          -31.941985
std                                           563.521530
min                                         -9999.000000
25%                                            -0.640000
50%                                            -0.160000
75%                                             0.350000
max                                             2.570000

Niño 4
       NINA4  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
count                                        1884.000000
mean                                          -32.007967
std                                           563.517573
min                                         -9999.000000
25%                                            -0.580000
50%                                            -0.170000
75%                                             0.260000
max                                             1.590000

SOI
       SOI from CRU  missing value 0.47 https://psl.noaa.gov/data/timeseries/month/
count                                        1920.000000
mean                                          -67.747068
std                                           820.188942
min                                         -9999.000000
25%                                            -0.802500
50%                                            -0.030000
75%                                             0.742500
max                                             4.070000

TNI
       TNI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
count                                        1884.000000
mean                                          -53.196596
std                                           726.726173
min                                         -9999.000000
25%                                            -0.846750
50%                                            -0.135500
75%                                             0.462000
max                                             4.638000

Explorar MEI.v2

In [17]:
with open(DATA_RAW / "meiv2.data", "r") as f:
    for _ in range(10):
        print(f.readline().rstrip())

1979     2026
1979     0.46     0.29    -0.05     0.22     0.27    -0.11    -0.10     0.47     0.38     0.23     0.53     0.63
1980     0.33     0.21     0.39     0.50     0.45     0.55     0.47     0.03     0.12     0.03    -0.08    -0.12
1981    -0.35    -0.23     0.33     0.42    -0.24    -0.69    -0.60    -0.33    -0.06    -0.16    -0.27    -0.20
1982    -0.43    -0.50    -0.28    -0.37    -0.11     0.63     1.65     1.91     1.68     1.77     2.13     2.36
1983     2.47     2.66     2.60     2.75     2.85     1.96     0.63    -0.17    -0.50    -0.53    -0.47    -0.50
1984    -0.55    -0.56    -0.17     0.06    -0.46    -0.69    -0.35    -0.19    -0.14    -0.19    -0.58    -0.29
1985    -0.26    -0.58    -0.60    -0.77    -1.23    -0.67    -0.10    -0.49    -0.56    -0.08    -0.06    -0.42
1986    -0.40    -0.34    -0.39    -0.53    -0.26     0.02     0.41     0.97     1.29     0.56     0.64     1.06
1987     1.03     1.16     1.57     1.75     1.97     2.07     1.88     1.46     1.26     1.18     0.91     0.79

Exploracion de ONI

In [18]:
with open(DATA_RAW / "oni.txt", "r") as f:
    for _ in range(10):
        print(f.readline().rstrip())

 1950  -1.53  -1.34  -1.16  -1.18  -1.07  -0.85  -0.54  -0.42  -0.39  -0.44  -0.60  -0.80
 1951  -0.82  -0.54  -0.17   0.18   0.36   0.58   0.70   0.89   0.99   1.15   1.04   0.81
 1952   0.53   0.37   0.34   0.29   0.20   0.00  -0.08   0.00   0.15   0.10   0.04   0.15
 1953   0.40   0.60   0.63   0.66   0.75   0.77   0.75   0.73   0.78   0.84   0.84   0.81
 1954   0.76   0.47  -0.05  -0.41  -0.54  -0.50  -0.64  -0.84  -0.90  -0.77  -0.73  -0.66
 1955  -0.68  -0.62  -0.69  -0.80  -0.79  -0.72  -0.68  -0.75  -1.09  -1.42  -1.67  -1.47
 1956  -1.11  -0.76  -0.63  -0.54  -0.52  -0.51  -0.57  -0.55  -0.46  -0.42  -0.43  -0.43
 1957  -0.25   0.06   0.41   0.72   0.92   1.11   1.25   1.32   1.33   1.39   1.53   1.74
 1958   1.81   1.66   1.27   0.93   0.74   0.64   0.57   0.43   0.39   0.44   0.50   0.61
 1959   0.61   0.62   0.52   0.33   0.20  -0.07  -0.18  -0.28  -0.09  -0.03   0.05  -0.04

Entender las fechas

In [19]:
nino34.head()

,Date,NINA34 missing value -99.99 https://psl.noaa.gov/data/timeseries/month/
0,1870-01-01,-1.00
1,1870-02-01,-1.20
2,1870-03-01,-0.83
3,1870-04-01,-0.81
4,1870-05-01,-1.27

In [20]:
print(nino34.columns)
print(nino34.iloc[:5, 0])

Index(['Date', '   NINA34  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/'], dtype='str')
0    1870-01-01
1    1870-02-01
2    1870-03-01
3    1870-04-01
4    1870-05-01
Name: Date, dtype: str

In [21]:
print(nino34.iloc[:, 0].dtype)

str

In [22]:
print(nino34.iloc[:, 0].min())
print(nino34.iloc[:, 0].max())

1870-01-01
2026-12-01

In [23]:
print(soi.head())
print(soi.dtypes)

         Date  \
0  1866-01-01
1  1866-02-01
2  1866-03-01
3  1866-04-01
4  1866-05-01

    SOI from CRU  missing value 0.47 https://psl.noaa.gov/data/timeseries/month/
0                                              -0.62
1                                              -0.12
2                                              -0.62
3                                              -0.65
4                                               0.04
Date                                                                                 str
 SOI from CRU  missing value 0.47 https://psl.noaa.gov/data/timeseries/month/    float64
dtype: object

In [24]:
with open(DATA_RAW / "meiv2.data", "r") as f:
    for i, line in enumerate(f):
        if i >= 15:
            break
        print(f"{i}: {line.rstrip()}")

0: 1979     2026
1: 1979     0.46     0.29    -0.05     0.22     0.27    -0.11    -0.10     0.47     0.38     0.23     0.53     0.63
2: 1980     0.33     0.21     0.39     0.50     0.45     0.55     0.47     0.03     0.12     0.03    -0.08    -0.12
3: 1981    -0.35    -0.23     0.33     0.42    -0.24    -0.69    -0.60    -0.33    -0.06    -0.16    -0.27    -0.20
4: 1982    -0.43    -0.50    -0.28    -0.37    -0.11     0.63     1.65     1.91     1.68     1.77     2.13     2.36
5: 1983     2.47     2.66     2.60     2.75     2.85     1.96     0.63    -0.17    -0.50    -0.53    -0.47    -0.50
6: 1984    -0.55    -0.56    -0.17     0.06    -0.46    -0.69    -0.35    -0.19    -0.14    -0.19    -0.58    -0.29
7: 1985    -0.26    -0.58    -0.60    -0.77    -1.23    -0.67    -0.10    -0.49    -0.56    -0.08    -0.06    -0.42
8: 1986    -0.40    -0.34    -0.39    -0.53    -0.26     0.02     0.41     0.97     1.29     0.56     0.64     1.06
9: 1987     1.03     1.16     1.57     1.75     1.97     2.07     1.88     1.46     1.26     1.18     0.91     0.79
10: 1988     0.63     0.33     0.17    -0.01    -0.39    -1.18    -1.77    -1.81    -1.81    -1.60    -1.71    -1.55
11: 1989    -1.12    -1.10    -1.24    -1.09    -1.03    -1.00    -1.08    -0.66    -0.53    -0.49    -0.36    -0.07
12: 1990     0.13     0.45     0.61     0.17     0.08     0.04     0.13     0.02     0.23    -0.06     0.12     0.31
13: 1991     0.19     0.09     0.21     0.20     0.36     0.97     0.91     0.37     0.53     0.97     1.04     1.23
14: 1992     1.68     1.59     1.72     1.98     1.68     1.51     0.61    -0.02     0.40     0.67     0.62     0.73

## Transformacion de los datos

In [25]:
for name, df in {
    "nino12": nino12,
    "nino3": nino3,
    "nino34": nino34,
    "nino4": nino4,
    "soi": soi,
    "tni": tni,
}.items():
    print(name, "->", df.columns.tolist())

nino12 -> ['Date', '   NINA12  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']
nino3 -> ['Date', '   NINA3  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']
nino34 -> ['Date', '   NINA34  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']
nino4 -> ['Date', '   NINA4  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']
soi -> ['Date', ' SOI from CRU  missing value 0.47 https://psl.noaa.gov/data/timeseries/month/']
tni -> ['Date', '   TNI  missing value -99.99 https://psl.noaa.gov/data/timeseries/month/']

Transformar a serie temporal y variables sentinelas

In [26]:
def prepare_csv_series(df, variable_name):
    """
    Homogeneiza una serie temporal de dos columnas:
    fecha y valor.
    """
    df = df.copy()

    # Homogeneizar nombres de columnas
    df.columns = ["date", variable_name]

    # Convertir fecha de string a datetime
    df["date"] = pd.to_datetime(df["date"])

    # Convertir sentinelas NOAA en valores faltantes
    df.loc[df[variable_name] <= -90, variable_name] = np.nan

    return df

In [27]:
# aplicacion de la funcion
nino12_clean = prepare_csv_series(nino12, "nino12")
nino3_clean = prepare_csv_series(nino3, "nino3")
nino34_clean = prepare_csv_series(nino34, "nino34")
nino4_clean = prepare_csv_series(nino4, "nino4")
soi_clean = prepare_csv_series(soi, "soi")
tni_clean = prepare_csv_series(tni, "tni")

In [29]:
nino34_clean.head()

        date  nino34
0 1870-01-01   -1.00
1 1870-02-01   -1.20
2 1870-03-01   -0.83
3 1870-04-01   -0.81
4 1870-05-01   -1.27

In [30]:
nino34_clean.dtypes

date      datetime64[us]
nino34           float64
dtype: object

In [31]:
# comprobar si los sentinelas se hiceron nan
for name, df in {
    "nino12": nino12_clean,
    "nino3": nino3_clean,
    "nino34": nino34_clean,
    "nino4": nino4_clean,
    "soi": soi_clean,
    "tni": tni_clean,
}.items():
    print(
        f"{name:8s} | "
        f"filas: {len(df):4d} | "
        f"missing: {df[name].isna().sum():3d} | "
        f"{df['date'].min().date()} -> {df['date'].max().date()}"
    )

nino12   | filas: 1884 | missing:   6 | 1870-01-01 -> 2026-12-01
nino3    | filas: 1884 | missing:   6 | 1870-01-01 -> 2026-12-01
nino34   | filas: 1884 | missing:   6 | 1870-01-01 -> 2026-12-01
nino4    | filas: 1884 | missing:   6 | 1870-01-01 -> 2026-12-01
soi      | filas: 1920 | missing:  13 | 1866-01-01 -> 2025-12-01
tni      | filas: 1884 | missing:  10 | 1870-01-01 -> 2026-12-01

Transformar los datos de MEI.v2

In [36]:
mei_wide = pd.read_csv(
    DATA_RAW / "meiv2.data",
    sep=r"\s+",
    skiprows=1,
    header=None
)

In [37]:
mei_wide.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1979,0.46,0.29,-0.05,0.22,0.27,-0.11,-0.10,0.47,0.38,0.23,0.53,0.63
1,1980,0.33,0.21,0.39,0.50,0.45,0.55,0.47,0.03,0.12,0.03,-0.08,-0.12
2,1981,-0.35,-0.23,0.33,0.42,-0.24,-0.69,-0.60,-0.33,-0.06,-0.16,-0.27,-0.20
3,1982,-0.43,-0.50,-0.28,-0.37,-0.11,0.63,1.65,1.91,1.68,1.77,2.13,2.36
4,1983,2.47,2.66,2.60,2.75,2.85,1.96,0.63,-0.17,-0.50,-0.53,-0.47,-0.50

In [38]:
mei_wide.shape

(48, 13)

poniendo nombres de columnas

In [40]:
month_names = [
    "jan", "feb", "mar", "apr", "may", "jun",
    "jul", "aug", "sep", "oct", "nov", "dec"
]

mei_wide.columns = ["year"] + month_names

In [41]:
mei_wide.head()

,year,jan,feb,mar,apr,may,jun,jul,aug,sep,oct,nov,dec
0,1979,0.46,0.29,-0.05,0.22,0.27,-0.11,-0.10,0.47,0.38,0.23,0.53,0.63
1,1980,0.33,0.21,0.39,0.50,0.45,0.55,0.47,0.03,0.12,0.03,-0.08,-0.12
2,1981,-0.35,-0.23,0.33,0.42,-0.24,-0.69,-0.60,-0.33,-0.06,-0.16,-0.27,-0.20
3,1982,-0.43,-0.50,-0.28,-0.37,-0.11,0.63,1.65,1.91,1.68,1.77,2.13,2.36
4,1983,2.47,2.66,2.60,2.75,2.85,1.96,0.63,-0.17,-0.50,-0.53,-0.47,-0.50

transformar el formato del tiempo

In [42]:
mei_long = mei_wide.melt(
    id_vars="year",
    var_name="month",
    value_name="mei"
)

In [43]:
mei_long.head(15)

    year month   mei
0   1979   jan  0.46
1   1980   jan  0.33
2   1981   jan -0.35
3   1982   jan -0.43
4   1983   jan  2.47
5   1984   jan -0.55
6   1985   jan -0.26
7   1986   jan -0.40
8   1987   jan  1.03
9   1988   jan  0.63
10  1989   jan -1.12
11  1990   jan  0.13
12  1991   jan  0.19
13  1992   jan  1.68
14  1993   jan  0.79

Construccion de la fecha

In [44]:
# meses a numeros
mont_map = {
    "jan": 1,
    "feb": 2,
    "mar": 3,
    "apr": 4,
    "may": 5,
    "jun": 6,
    "jul": 7,
    "aug": 8,
    "sep": 9,
    "oct": 10,
    "nov": 11,
    "dec": 12
}

mei_long["month_num"] = mei_long["month"].map(mont_map)

In [45]:
mei_long["date"] = pd.to_datetime(
    dict(
        year=mei_long["year"],
        month=mei_long["month_num"],
        day=1
    )
)

In [46]:
mei_clean = (
    mei_long[["date", "mei"]]
    .sort_values("date")
    .reset_index(drop=True)
)

In [47]:
mei_clean.head()

        date   mei
0 1979-01-01  0.46
1 1979-02-01  0.29
2 1979-03-01 -0.05
3 1979-04-01  0.22
4 1979-05-01  0.27

sentinelas de mei

In [49]:
mei_clean["mei"].min()

np.float64(-999.0)

In [50]:
mei_clean.loc[mei_clean["mei"] <= -90, "mei"] = np.nan

In [51]:
mei_clean.tail()

          date   mei
571 2026-08-01  2.54
572 2026-09-01   NaN
573 2026-10-01   NaN
574 2026-11-01   NaN
575 2026-12-01   NaN

Estructuracion para los datos de ONI

In [52]:
oni_wide = pd.read_csv(
    DATA_RAW / "oni.txt",
    sep=r"\s+",
    header=None
)

In [53]:
oni_wide.head()
oni_wide.shape

(77, 13)

In [54]:
oni_wide.columns = ["year"] + month_names

In [55]:
oni_long = oni_wide.melt(
    id_vars="year",
    var_name="month",
    value_name="oni"
)

In [56]:
oni_long["month_num"] = oni_long["month"].map(mont_map)

In [57]:
oni_long["date"] = pd.to_datetime(
    dict(
        year=oni_long["year"],
        month=oni_long["month_num"],
        day=1
    )
)

In [58]:
oni_clean = (
    oni_long[["date", "oni"]]
    .sort_values("date")
    .reset_index(drop=True)
)

In [59]:
oni_clean.loc[oni_clean["oni"] <= -90, "oni"] = np.nan

In [60]:
oni_clean.tail(12)

          date   oni
912 2026-01-01 -0.39
913 2026-02-01 -0.21
914 2026-03-01  0.11
915 2026-04-01  0.46
916 2026-05-01  0.95
917 2026-06-01  1.39
918 2026-07-01  1.80
919 2026-08-01   NaN
920 2026-09-01   NaN
921 2026-10-01   NaN
922 2026-11-01   NaN
923 2026-12-01   NaN

Se tienen todos los datos homogeneos

In [61]:
clean_datasets = {
    "nino12": nino12_clean,
    "nino3": nino3_clean,
    "nino34": nino34_clean,
    "nino4": nino4_clean,
    "soi": soi_clean,
    "tni": tni_clean,
    "mei": mei_clean,
    "oni": oni_clean,
}

summary = []

for name, df in clean_datasets.items():
    summary.append({
        "variable": name,
        "observations": len(df),
        "start": df["date"].min(),
        "end": df["date"].max(),
        "missing": df[name].isna().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

  variable  observations      start        end  missing
0   nino12          1884 1870-01-01 2026-12-01        6
1    nino3          1884 1870-01-01 2026-12-01        6
2   nino34          1884 1870-01-01 2026-12-01        6
3    nino4          1884 1870-01-01 2026-12-01        6
4      soi          1920 1866-01-01 2025-12-01       13
5      tni          1884 1870-01-01 2026-12-01       10
6      mei           576 1979-01-01 2026-12-01        4
7      oni           924 1950-01-01 2026-12-01        5

In [62]:
# rangos temporales efectivos
for name, df in clean_datasets.items():
    print(
        f"{name:8s}: "
        f"{df['date'].min().date()} → "
        f"{df['date'].max().date()} | "
        f"NaN = {df[name].isna().sum()}"
    )

nino12  : 1870-01-01 → 2026-12-01 | NaN = 6
nino3   : 1870-01-01 → 2026-12-01 | NaN = 6
nino34  : 1870-01-01 → 2026-12-01 | NaN = 6
nino4   : 1870-01-01 → 2026-12-01 | NaN = 6
soi     : 1866-01-01 → 2025-12-01 | NaN = 13
tni     : 1870-01-01 → 2026-12-01 | NaN = 10
mei     : 1979-01-01 → 2026-12-01 | NaN = 4
oni     : 1950-01-01 → 2026-12-01 | NaN = 5

### Construir el dataset maestro

In [82]:
from functools import reduce

dataframes = [
    nino12_clean,
    nino3_clean,
    nino34_clean,
    nino4_clean,
    soi_clean,
    tni_clean,
    mei_clean,
    oni_clean,
]

enso_master = reduce(
    lambda left, right: pd.merge(
        left,
        right,
        on="date",
        how="outer"
    ),
    dataframes
)

enso_master = (
    enso_master
    .sort_values("date")
    .reset_index(drop=True)
)

In [65]:
enso_master.head(10)

        date  nino12  nino3  nino34  nino4   soi  tni  mei  oni
0 1866-01-01     NaN    NaN     NaN    NaN -0.62  NaN  NaN  NaN
1 1866-02-01     NaN    NaN     NaN    NaN -0.12  NaN  NaN  NaN
2 1866-03-01     NaN    NaN     NaN    NaN -0.62  NaN  NaN  NaN
3 1866-04-01     NaN    NaN     NaN    NaN -0.65  NaN  NaN  NaN
4 1866-05-01     NaN    NaN     NaN    NaN  0.04  NaN  NaN  NaN
5 1866-06-01     NaN    NaN     NaN    NaN -0.82  NaN  NaN  NaN
6 1866-07-01     NaN    NaN     NaN    NaN -0.34  NaN  NaN  NaN
7 1866-08-01     NaN    NaN     NaN    NaN  0.36  NaN  NaN  NaN
8 1866-09-01     NaN    NaN     NaN    NaN -0.18  NaN  NaN  NaN
9 1866-10-01     NaN    NaN     NaN    NaN  0.07  NaN  NaN  NaN

In [66]:
enso_master.tail()

           date  nino12  nino3  nino34  nino4  soi  tni   mei  oni
1927 2026-08-01     NaN    NaN     NaN    NaN  NaN  NaN  2.54  NaN
1928 2026-09-01     NaN    NaN     NaN    NaN  NaN  NaN   NaN  NaN
1929 2026-10-01     NaN    NaN     NaN    NaN  NaN  NaN   NaN  NaN
1930 2026-11-01     NaN    NaN     NaN    NaN  NaN  NaN   NaN  NaN
1931 2026-12-01     NaN    NaN     NaN    NaN  NaN  NaN   NaN  NaN

In [67]:
enso_master["date"].duplicated().sum()

np.int64(0)

In [68]:
for name, df in clean_datasets.items():
    duplicates = df["date"].duplicated().sum()
    print(f"{name:8s}: {duplicates} fechas duplicadas")

nino12  : 0 fechas duplicadas
nino3   : 0 fechas duplicadas
nino34  : 0 fechas duplicadas
nino4   : 0 fechas duplicadas
soi     : 0 fechas duplicadas
tni     : 0 fechas duplicadas
mei     : 0 fechas duplicadas
oni     : 0 fechas duplicadas

In [69]:
expected_dates = pd.date_range(
    start=enso_master["date"].min(),
    end=enso_master["date"].max(),
    freq="MS"
)

len(expected_dates)

1932

In [70]:
missing_dates = expected_dates.difference(enso_master["date"])

len(missing_dates)

0

In [71]:
enso_master.isna().sum()

date         0
nino12      54
nino3       54
nino34      54
nino4       54
soi         25
tni         58
mei       1360
oni       1013
dtype: int64

In [72]:
missing_summary = pd.DataFrame({
    "missing": enso_master.isna().sum(),
    "percentage": enso_master.isna().mean() * 100
})

missing_summary.round(2)

        missing  percentage
date          0        0.00
nino12       54        2.80
nino3        54        2.80
nino34       54        2.80
nino4        54        2.80
soi          25        1.29
tni          58        3.00
mei        1360       70.39
oni        1013       52.43

### Construccion de los dos datasets

Dataset historico (mayor cantidad de datos)

In [73]:
historical_columns = [
    "date",
    "nino12",
    "nino3",
    "nino34",
    "nino4",
    "soi",
    "tni",
]

enso_historical = enso_master[historical_columns].copy()

In [74]:
enso_historical.head()

        date  nino12  nino3  nino34  nino4   soi  tni
0 1866-01-01     NaN    NaN     NaN    NaN -0.62  NaN
1 1866-02-01     NaN    NaN     NaN    NaN -0.12  NaN
2 1866-03-01     NaN    NaN     NaN    NaN -0.62  NaN
3 1866-04-01     NaN    NaN     NaN    NaN -0.65  NaN
4 1866-05-01     NaN    NaN     NaN    NaN  0.04  NaN

In [75]:
enso_historical = (
    enso_historical
    .dropna()
    .reset_index(drop=True)
)

In [76]:
print(enso_historical.shape)
print(
    enso_historical["date"].min(),
    "→",
    enso_historical["date"].max()
)

(1857, 7)
1870-03-01 00:00:00 → 2025-12-01 00:00:00

Dataset moderno

In [83]:
modern_columns = [
    "date",
    "nino12",
    "nino3",
    "nino34",
    "nino4",
    "soi",
    "tni",
    "mei",
    "oni",
]

enso_modern = (
    enso_master.loc[
        enso_master["date"] >= "1979-01-01",
        modern_columns
    ]
    .dropna()
    .reset_index(drop=True)
)

print(enso_modern.shape)
print(
    enso_modern["date"].min(),
    "→",
    enso_modern["date"].max()
)

(562, 9)
1979-01-01 00:00:00 → 2025-12-01 00:00:00

Validacion final

In [84]:
dataset_comparison = pd.DataFrame({
    "dataset": [
        "Master",
        "Historical",
        "Modern"
    ],
    "observations": [
        len(enso_master),
        len(enso_historical),
        len(enso_modern)
    ],
    "start": [
        enso_master["date"].min(),
        enso_historical["date"].min(),
        enso_modern["date"].min()
    ],
    "end": [
        enso_master["date"].max(),
        enso_historical["date"].max(),
        enso_modern["date"].max()
    ],
    "variables": [
        len(enso_master.columns) - 1,
        len(enso_historical.columns) - 1,
        len(enso_modern.columns) - 1
    ]
})

dataset_comparison

      dataset  observations      start        end  variables
0      Master          1932 1866-01-01 2026-12-01          8
1  Historical          1857 1870-03-01 2025-12-01          6
2      Modern           562 1979-01-01 2025-12-01          8

guardar los datos procesados

In [85]:
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

enso_master.to_csv(
    DATA_PROCESSED / "enso_master.csv",
    index=False
)

enso_historical.to_csv(
    DATA_PROCESSED / "enso_historical.csv",
    index=False
)

enso_modern.to_csv(
    DATA_PROCESSED / "enso_modern.csv",
    index=False
)


## Conclusiones del entendimiento de datos

- Las fuentes contienen información climática mensual relacionada con ENSO.
- Los índices Niño 1+2, Niño 3, Niño 3.4, Niño 4, SOI y TNI poseen
  series históricas extensas.
- ONI comienza en 1950 y MEI.v2 en 1979.
- Las fuentes originales utilizan diferentes estructuras de almacenamiento.
- Los códigos sentinela negativos fueron convertidos a valores faltantes.
- Las fechas fueron homogeneizadas a frecuencia mensual.
- Se construyó un dataset maestro mediante integración temporal.
- Se conservaron dos conjuntos analíticos:
  - **Historical:** mayor cobertura temporal y menor número de indicadores.
  - **Modern:** menor cobertura temporal pero incorpora MEI.v2 y ONI.
- Estos conjuntos todavía no representan matrices finales de Machine Learning.

## Siguiente etapa

Realizar un análisis exploratorio de datos (EDA) para estudiar:

- Evolución temporal de los indicadores.
- Distribuciones.
- Eventos extremos.
- Relaciones entre variables.
- Correlaciones.
- Comportamiento durante episodios conocidos de El Niño y La Niña.
- Posibles problemas de redundancia entre indicadores.